### PR TITLE
Upgrade to Bootstrap 5

### PR DESCRIPTION
**Pull request by oliverroick**
Implements [#45](https://github.com/yuvipanda/jupyterhub-fancy-profiles/issues/45)

- Updates form CSS classes, so we're using more Bootstrap CSS classes, specifically for error messaging. This allows us to remove some of the custom classes. 
- Update typography: Use `h2` elements instead of custom label heading

### CODE REVIEW

**Review by GeorgianaElena — APPROVED** [review]
Thank you @oliverroick ✨ ! Do you want to fix the conflicts in this PR so we can merge and try this out in a JupyterHub 5 setup?

**Comment by oliverroick** [comment]
@GeorgianaElena I fixed the failing tests. This should be good to go now.

**Comment by yuvipanda** [comment]
Unfortunately it looks like Bootstrap 5 will now automatically switch to 'dark mode' if your system is using dark mode, and our selection CSS looks pretty bad on it:

image

image

**Comment by yuvipanda** [comment]
I fixed some of them but not all. I'll try get back to this tomorrow.

**Comment by yuvipanda** [comment]
image

image

The titles of the dropdown items are still the wrong color, and I'm not sure what css selector those are.

**Comment by yuvipanda** [comment]
Alright, all fixed!

**Pull request merged**
